"""Writes the generated project tree.

Every template below is pinned byte for byte by the tests, so a
project generated by either implementation is indistinguishable.
"""

from __future__ import annotations

import os
from collections.abc import Sequence
from dataclasses import dataclass, field
from pathlib import Path

from .profiles import Tooling

__all__ = [
    "ProjectSpec",
    "render_pyproject",
    "render_vscode_settings",
    "write_project_files",
    "venv_python_path",
    "IS_WINDOWS",
]


# Resolved once, at import. Tests override this attribute to render the other
# platform's layout; patching os.name instead would also repoint pathlib, which
# then refuses to build a WindowsPath on POSIX (and vice versa).
IS_WINDOWS = os.name == "nt"


def venv_python_path(prefix: str = ".venv") -> str:
    if IS_WINDOWS:
        return f"{prefix}/Scripts/python.exe"
    return f"{prefix}/bin/python"


@dataclass
class ProjectSpec:
    project_name: str
    pkg_name: str
    profile: str
    files_mode: str
    framework: str
    tooling: Tooling
    root: Path
    dev_packages: list[str] = field(default_factory=list)
    runtime_packages: list[str] = field(default_factory=list)
    extensions: list[str] = field(default_factory=list)
    py_major: int = 3
    py_minor: int = 9
    requires_python: str = ">=3.9"
    example_workflow: bool = False

    @property
    def src_dir(self) -> Path:
        return self.root / "src" / self.pkg_name


# ---------------------------------------------------------------------------
# Small renderers
# ---------------------------------------------------------------------------
def _toml_list(items: Sequence[str]) -> str:
    # An empty list still yields the blank line between the brackets.
    if not items:
        return ""
    return "\n".join(f'    "{item}",' for item in items)


def _json_list(items: Sequence[str]) -> str:
    if not items:
        return ""
    return ",\n".join(f'        "{item}"' for item in items)


def render_pyproject(spec: ProjectSpec) -> str:
    t = spec.tooling
    parts = [
        "[build-system]\n"
        'requires = ["setuptools>=68"]\n'
        'build-backend = "setuptools.build_meta"\n'
        "\n"
        "[project]\n"
        f'name = "{spec.project_name}"\n'
        'version = "0.1.0"\n'
        'description = ""\n'
        f'requires-python = "{spec.requires_python}"\n'
        'readme = "README.md"\n'
        "dependencies = [\n"
        f"{_toml_list(spec.runtime_packages)}\n"
        "]\n"
        "\n"
        "[dependency-groups]\n"
        "dev = [\n"
        f"{_toml_list(spec.dev_packages)}\n"
        "]\n"
        "\n"
    ]

    if t.quality == "ruff":
        parts.append(
            "\n[tool.ruff]\n"
            "line-length = 100\n"
            f'target-version = "py{spec.py_major}{spec.py_minor}"\n'
            "\n"
            "[tool.ruff.lint]\n"
            'select = ["E", "F", "I", "B", "UP"]\n'
        )

    if t.testing in ("pytest", "pytest_cov"):
        parts.append("\n[tool.pytest.ini_options]\ntestpaths = [\"tests\"]\n")

    if t.type_checker == "mypy":
        parts.append(
            "\n[tool.mypy]\n"
            f'python_version = "{spec.py_major}.{spec.py_minor}"\n'
            "ignore_missing_imports = true\n"
        )

    if t.quality in ("black_pylint", "black_flake8"):
        parts.append('\n[tool.black]\nline-length = 100\ntarget-version = ["py39"]\n')

    return "".join(parts)


def render_vscode_settings(spec: ProjectSpec) -> str:
    t = spec.tooling
    formatter = ""
    if t.quality == "ruff":
        formatter = "charliermarsh.ruff"
    elif t.quality in ("black_pylint", "black_flake8"):
        formatter = "ms-python.black-formatter"

    pytest_enabled = "true" if t.testing in ("pytest", "pytest_cov") else "false"
    format_on_save = "false" if spec.profile == "learner" else "true"

    code_actions = '        "source.organizeImports": "explicit"'
    if formatter:
        code_actions += ',\n        "source.fixAll": "explicit"'

    python_block = ""
    if formatter:
        python_block = (
            ',\n    "[python]": {\n'
            f'        "editor.defaultFormatter": "{formatter}"\n'
            "    }"
        )

    return (
        "{\n"
        f'    "python.defaultInterpreterPath": '
        f'"${{workspaceFolder}}/{venv_python_path()}",\n'
        f'    "python.testing.pytestEnabled": {pytest_enabled},\n'
        '    "python.testing.pytestArgs": ["tests"],\n'
        f'    "editor.formatOnSave": {format_on_save},\n'
        '    "editor.codeActionsOnSave": {\n'
        f"{code_actions}\n"
        "    }"
        f"{python_block}\n"
        "}\n"
    )


def render_vscode_extensions(extensions: Sequence[str]) -> str:
    return '{\n    "recommendations": [\n' f"{_json_list(extensions)}\n" "    ]\n}\n"


GITIGNORE = """\
.venv/
__pycache__/
*.pyc
.pytest_cache/
.mypy_cache/
.ruff_cache/
*.egg-info/
dist/
build/
.env
.DS_Store
.ipynb_checkpoints/
models/*.pkl
models/*.pt
models/*.pth
models/*.keras
models/*.onnx
"""

ENV_EXAMPLE = "# Copy to .env when the project needs environment variables.\n"

NOTEBOOKS_README = """\
# Notebooks

Keep exploratory work here. Move reusable logic into `src/`.
"""

SKLEARN_EXAMPLE = '''\
"""Small scikit-learn baseline example — educational, not production-ready."""

import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split


def main() -> None:
    rng = np.random.default_rng(42)
    X = rng.normal(size=(300, 4))
    y = (X[:, 0] + 0.5 * X[:, 1] > 0).astype(int)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )
    model = RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    print(f"Baseline accuracy: {accuracy_score(y_test, predictions):.3f}")


if __name__ == "__main__":
    main()
'''

PYTORCH_EXAMPLE = '''\
"""Tiny PyTorch training example — educational, not production-ready."""

import torch
from torch import nn


def main() -> None:
    torch.manual_seed(42)
    X = torch.randn(256, 4)
    y = (X[:, 0] + 0.5 * X[:, 1] > 0).float().unsqueeze(1)

    model = nn.Sequential(nn.Linear(4, 8), nn.ReLU(), nn.Linear(8, 1))
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-2)
    loss_fn = nn.BCEWithLogitsLoss()

    for _ in range(100):
        loss = loss_fn(model(X), y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    with torch.no_grad():
        accuracy = ((torch.sigmoid(model(X)) > 0.5) == y).float().mean()
    print(f"Baseline accuracy: {accuracy.item():.3f}")


if __name__ == "__main__":
    main()
'''


def _example_readme(framework: str) -> str:
    return f"""\
# Example workflow

This profile was created with **{framework}**. No model architecture is
forced into the generated project. Add an example here that matches your
actual dataset, task, and framework.

This directory is for learning and demonstration; examples are not
production-ready pipelines.
"""


# ---------------------------------------------------------------------------
# Source templates
# ---------------------------------------------------------------------------
def _init_py(spec: ProjectSpec) -> str:
    return f'"""{spec.project_name} package."""\n\n__version__ = "0.1.0"\n'


def _main_py(spec: ProjectSpec) -> str:
    return (
        f'"""Entry point for {spec.project_name}."""\n'
        "\n\n"
        "def main() -> None:\n"
        f'    """Run {spec.project_name}."""\n'
        f'    print("Hello from {spec.project_name}")\n'
        "\n\n"
        'if __name__ == "__main__":\n'
        "    main()\n"
    )


def _cli_py(spec: ProjectSpec) -> str:
    name = spec.project_name
    if spec.framework == "typer":
        return (
            f'"""Command-line interface for {name}."""\n\n'
            "import typer\n\n"
            "app = typer.Typer()\n\n\n"
            "@app.command()\n"
            "def main() -> None:\n"
            f'    """Run {name}."""\n'
            f'    typer.echo("Hello from {name}")\n'
            "\n\n"
            'if __name__ == "__main__":\n'
            "    app()\n"
        )
    if spec.framework == "click":
        return (
            f'"""Command-line interface for {name}."""\n\n'
            "import click\n\n\n"
            "@click.command()\n"
            "def main() -> None:\n"
            f'    """Run {name}."""\n'
            f'    click.echo("Hello from {name}")\n'
            "\n\n"
            'if __name__ == "__main__":\n'
            "    main()\n"
        )
    return (
        f'"""Command-line interface for {name}."""\n\n'
        "import argparse\n\n\n"
        "def main() -> None:\n"
        f'    """Run {name}."""\n'
        f'    parser = argparse.ArgumentParser(description="{name}")\n'
        "    parser.parse_args()\n"
        f'    print("Hello from {name}")\n'
        "\n\n"
        'if __name__ == "__main__":\n'
        "    main()\n"
    )


def _web_main_py(spec: ProjectSpec) -> str:
    name = spec.project_name
    if spec.framework == "fastapi":
        return (
            f'"""FastAPI application entry point for {name}."""\n\n'
            "from fastapi import FastAPI\n\n"
            f'app = FastAPI(title="{name}")\n\n\n'
            '@app.get("/")\n'
            "def root() -> dict[str, str]:\n"
            '    """Return a simple greeting."""\n'
            f'    return {{"message": "Hello from {name}"}}\n'
        )
    if spec.framework == "flask":
        return (
            f'"""Flask application entry point for {name}."""\n\n'
            "from flask import Flask\n\n"
            "app = Flask(__name__)\n\n\n"
            '@app.get("/")\n'
            "def root() -> str:\n"
            '    """Return a simple greeting."""\n'
            f'    return "Hello from {name}"\n'
        )
    return _main_py(spec)


def _readme(spec: ProjectSpec) -> str:
    return (
        f"# {spec.project_name}\n\n"
        f"Generated by **mkpj** with the **{spec.profile}** profile.\n\n"
        "## Test\n\n"
        "```bash\n"
        f"{venv_python_path()} -m pytest\n"
        "```\n"
    )


def _test_main(pkg_name: str) -> str:
    return (
        f"from {pkg_name}.main import main\n\n\n"
        "def test_main_runs(capsys):\n"
        "    main()\n"
        "    captured = capsys.readouterr()\n"
        '    assert "Hello" in captured.out\n'
    )


def _test_cli(pkg_name: str) -> str:
    return (
        f"from {pkg_name}.cli import main\n\n\n"
        "def test_cli_entrypoint_exists():\n"
        "    assert callable(main)\n"
    )


def _test_app(pkg_name: str) -> str:
    return (
        f"from {pkg_name}.main import app\n\n\n"
        "def test_app_exists():\n"
        "    assert app is not None\n"
    )


# ---------------------------------------------------------------------------
# Writer
# ---------------------------------------------------------------------------
def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def write_project_files(spec: ProjectSpec) -> None:
    root = spec.root
    _write(root / "pyproject.toml", render_pyproject(spec))
    _write(root / "README.md", _readme(spec))
    _write(root / ".gitignore", GITIGNORE)

    if spec.profile != "minimal":
        _write(root / ".env.example", ENV_EXAMPLE)

    _write(spec.src_dir / "__init__.py", _init_py(spec))

    if spec.files_mode == "cli":
        _write(spec.src_dir / "cli.py", _cli_py(spec))
    elif spec.files_mode == "web":
        _write(spec.src_dir / "main.py", _web_main_py(spec))
    else:
        _write(spec.src_dir / "main.py", _main_py(spec))

    if spec.profile != "minimal":
        _write(root / "tests" / "__init__.py", "")
        if spec.files_mode == "cli":
            _write(root / "tests" / "test_cli.py", _test_cli(spec.pkg_name))
        elif spec.files_mode == "web":
            if spec.framework in ("fastapi", "flask"):
                _write(root / "tests" / "test_app.py", _test_app(spec.pkg_name))
            else:
                _write(root / "tests" / "test_main.py", _test_main(spec.pkg_name))
        else:
            _write(root / "tests" / "test_main.py", _test_main(spec.pkg_name))

    if spec.profile in ("data", "ml", "dl", "research"):
        _write(root / "notebooks" / "README.md", NOTEBOOKS_README)

    if spec.profile == "library":
        _write(spec.src_dir / "py.typed", "")

    if spec.profile == "cli":
        with open(root / "pyproject.toml", "a", encoding="utf-8") as handle:
            handle.write(
                "\n[project.scripts]\n"
                f'{spec.project_name} = "{spec.pkg_name}.cli:main"\n'
            )

    if spec.example_workflow:
        write_example(spec)


def write_example(spec: ProjectSpec) -> None:
    if spec.profile not in ("ml", "dl"):
        return
    examples = spec.root / "examples"
    examples.mkdir(parents=True, exist_ok=True)

    if spec.profile == "ml" and spec.framework == "scikit-learn":
        _write(examples / "baseline.py", SKLEARN_EXAMPLE)
    elif spec.profile == "dl" and spec.framework == "pytorch":
        _write(examples / "baseline.py", PYTORCH_EXAMPLE)
    else:
        _write(examples / "README.md", _example_readme(spec.framework))


def write_vscode(spec: ProjectSpec) -> None:
    vscode = spec.root / ".vscode"
    vscode.mkdir(parents=True, exist_ok=True)
    _write(vscode / "settings.json", render_vscode_settings(spec))
    _write(vscode / "extensions.json", render_vscode_extensions(spec.extensions))
